version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache2
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db2
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8009:80
    db2:
        container_name: db2
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9909:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
             - '8083:80'
        restart: always
        environment:
            PMA_HOST: db2
            UPLOAD_LIMIT: 200M
        depends_on:
                  - db2                